apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: 2018-08-04T09:37:45Z
  labels:
    build: nationalparks
  name: nationalparks
  namespace: 3890-parks-dev
  resourceVersion: "29295241"
  selfLink: /apis/build.openshift.io/v1/namespaces/3890-parks-dev/buildconfigs/nationalparks
  uid: 0ac2bf3d-97ca-11e8-9a19-0220bffb280e
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nationalparks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.2
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ktijU6Z14fkFWeNUFNFN
    type: GitHub
  - generic:
      secret: _b947V67WJ1-iY_gypIO
    type: Generic
status:
  lastVersion: 2
