apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: 2018-08-04T09:37:24Z
  labels:
    name: mongodb
  name: mongodb-internal
  namespace: 3890-parks-dev
  resourceVersion: "29282812"
  selfLink: /api/v1/namespaces/3890-parks-dev/services/mongodb-internal
  uid: fe2c2d6d-97c9-11e8-9a19-0220bffb280e
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
