apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-04T09:37:59Z
  labels:
    app: parksmap
  name: parksmap
  namespace: 3890-parks-dev
  resourceVersion: "29283692"
  selfLink: /api/v1/namespaces/3890-parks-dev/services/parksmap
  uid: 12fc7df2-97ca-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.159.66
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: parksmap
    deploymentconfig: parksmap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
