apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-04T09:37:25Z
  labels:
    name: mongodb
  name: mongodb
  namespace: 3890-parks-dev
  resourceVersion: "29282829"
  selfLink: /api/v1/namespaces/3890-parks-dev/services/mongodb
  uid: ff00cd2e-97c9-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.67.237
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
