apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-08-04T09:37:34Z
  generation: 11
  labels:
    app: mlbparks
    type: parksmap-backend
  name: mlbparks
  namespace: 3890-parks-dev
  resourceVersion: "29298854"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3890-parks-dev/deploymentconfigs/mlbparks
  uid: 0407e333-97ca-11e8-9a19-0220bffb280e
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mlbparks
    deploymentconfig: mlbparks
    type: parksmap-backend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: mlbparks
        deploymentconfig: mlbparks
        type: parksmap-backend
    spec:
      containers:
      - env:
        - name: APPNAME
          value: MLB Parks (Dev)
        - name: DB_HOST
          value: mongodb
        - name: DB_PORT
          value: "27017"
        - name: DB_USERNAME
          value: mongodb
        - name: DB_PASSWORD
          value: mongodb
        - name: DB_NAME
          value: parks
        - name: DB_REPLICASET
          value: rs0
        image: docker-registry.default.svc:5000/3890-parks-dev/mlbparks:1.0-2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - echo
            - ok
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mlbparks
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ws/healthz/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/eap/standalone/configuration/application-users.properties
          name: jboss-config
          subPath: application-users.properties
        - mountPath: /opt/eap/standalone/configuration/application-roles.properties
          name: jboss-config1
          subPath: application-roles.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: mlbparks-config
        name: jboss-config
      - configMap:
          defaultMode: 420
          name: mlbparks-config
        name: jboss-config1
  test: false
  triggers: []
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-04T09:56:47Z
    lastUpdateTime: 2018-08-04T09:56:47Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-04T10:12:00Z
    lastUpdateTime: 2018-08-04T10:12:02Z
    message: replication controller "mlbparks-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: Manual
    message: manual change
  latestVersion: 2
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
