apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-08-04T09:37:26Z
  generation: 9
  labels:
    app: nexus3
  name: nexus3
  namespace: 3890-nexus
  resourceVersion: "29285399"
  selfLink: /apis/apps.openshift.io/v1/namespaces/3890-nexus/deploymentconfigs/nexus3
  uid: ff3e15d7-97c9-11e8-9a19-0220bffb280e
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: nexus3
    deploymentconfig: nexus3
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: nexus3
        deploymentconfig: nexus3
    spec:
      containers:
      - image: docker.io/sonatype/nexus3@sha256:e57d22b59b607d055f9241f1613073ec1b46c37afae30d67707072f19a87d244
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - echo
            - ok
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nexus3
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /repository/maven-public/
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus3-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus3-volume-1
        persistentVolumeClaim:
          claimName: nexus-pvc
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nexus3
      from:
        kind: ImageStreamTag
        name: nexus3:latest
        namespace: 3890-nexus
      lastTriggeredImage: docker.io/sonatype/nexus3@sha256:e57d22b59b607d055f9241f1613073ec1b46c37afae30d67707072f19a87d244
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-04T09:42:43Z
    lastUpdateTime: 2018-08-04T09:42:43Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-04T09:38:08Z
    lastUpdateTime: 2018-08-04T09:42:44Z
    message: replication controller "nexus3-3" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 3
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
