apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-04T09:42:47Z
  labels:
    app: nexus3
  name: nexus-registry
  namespace: 3890-nexus
  resourceVersion: "29285423"
  selfLink: /api/v1/namespaces/3890-nexus/services/nexus-registry
  uid: beebd630-97ca-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.21.139
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nexus3
    deploymentconfig: nexus3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
