apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-08-04T09:37:26Z
  labels:
    app: nexus3
  name: nexus3
  namespace: 3890-nexus
  resourceVersion: "29282891"
  selfLink: /api/v1/namespaces/3890-nexus/services/nexus3
  uid: ff4e1973-97c9-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.164.250
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus3
    deploymentconfig: nexus3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
