apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: 2018-08-04T09:37:49Z
  labels:
    build: nationalparks
  name: nationalparks
  namespace: 3890-parks-prod
  resourceVersion: "29283540"
  selfLink: /apis/build.openshift.io/v1/namespaces/3890-parks-prod/buildconfigs/nationalparks
  uid: 0d63a61f-97ca-11e8-9a19-0220bffb280e
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nationalparks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.2
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: pRmrQ_Ql90LA-GobJTF2
    type: GitHub
  - generic:
      secret: vFV-OS96HN25ao1KeKmv
    type: Generic
status:
  lastVersion: 0
