apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-04T09:38:11Z
  labels:
    app: parksmap-green
  name: parksmap-green
  namespace: 3890-parks-prod
  resourceVersion: "29283859"
  selfLink: /api/v1/namespaces/3890-parks-prod/services/parksmap-green
  uid: 1a6e4130-97ca-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.60.229
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: parksmap-green
    deploymentconfig: parksmap-green
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
