apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-04T09:38:12Z
  labels:
    app: parksmap-blue
  name: parksmap-blue
  namespace: 3890-parks-prod
  resourceVersion: "29283868"
  selfLink: /api/v1/namespaces/3890-parks-prod/services/parksmap-blue
  uid: 1af04589-97ca-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.65.228
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: parksmap-blue
    deploymentconfig: parksmap-blue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
