apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  creationTimestamp: 2018-08-04T09:37:25Z
  labels:
    app: sonarqube_db
    template: postgresql-persistent-template
  name: postgresql
  namespace: 3890-sonarqube
  resourceVersion: "29282825"
  selfLink: /api/v1/namespaces/3890-sonarqube/services/postgresql
  uid: fef24808-97c9-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.131.207
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
