apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-08-04T09:37:28Z
  labels:
    app: sonarqube
  name: sonarqube
  namespace: 3890-sonarqube
  resourceVersion: "29282991"
  selfLink: /api/v1/namespaces/3890-sonarqube/services/sonarqube
  uid: 008ecca2-97ca-11e8-9a19-0220bffb280e
spec:
  clusterIP: 172.30.31.223
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: sonarqube
    deploymentconfig: sonarqube
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
