apiVersion: v1
kind: Template
metadata:
  name: parks-app-template
parameters:
  - name: GUID
    value: "xxxx"
  - name: CLUSTER
    value: "HOGE_CLUSTER"
  - name: REPO
    value: "FUGA REPO"
objects:
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      labels:
        name: "mlbparks-pipeline"
      name: "mlbparks-pipeline"
    spec:
      source:
        type: "Git"
        git: 
          uri: "https://github.com/hisasue/ocp_advdev.git"
        contextDir: "MLBParks"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          env:
            - name: GUID
              value: ${GUID}
            - name: CLUSTER
              value: ${CLUSTER}
            - name: REPO
              value: ${REPO}
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      labels:
        name: "nationalparks-pipeline"
      name: "nationalparks-pipeline"
    spec:
      source:
        type: "Git"
        git: 
          uri: "https://github.com/hisasue/ocp_advdev.git"
        contextDir: "Nationalparks"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          env:
            - name: GUID
              value: ${GUID}
            - name: CLUSTER
              value: ${CLUSTER}
            - name: REPO
              value: ${REPO}
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      labels:
        name: "parksmap-pipeline"
      name: "parksmap-pipeline"
    spec:
      source:
        contextDir: "ParksMap"
        type: "Git"
        git: 
          uri: "https://github.com/hisasue/ocp_advdev.git"
      strategy:
        type: "JenkinsPipeline"
        jenkinsPipelineStrategy:
          env:
            - name: GUID
              value: ${GUID}
            - name: CLUSTER
              value: ${CLUSTER}
            - name: REPO
              value: ${REPO}
