apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-template
parameters:
  - name: GUID
    value: "xxxx"
  - name: CLUSTER
    value: "HOGE_CLUSTER"
  - name: REPO
    value: "FUGA REPO"
objects:
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "jenkins-slave-maven-appdev"
    spec:
      source:
        dockerfile: |
          FROM docker.io/openshift/jenkins-slave-maven-centos7:v3.9
          USER root
          RUN yum -y install skopeo apb && yum clean all
          USER 1001
        type: Dockerfile
      strategy:
        dockerStrategy:
          from:
            kind: "ImageStreamTag"
            name: "jenkins-slave-maven-appdev:v3.9"
            #name: "nexus-registry-80ff-nexus.apps.na39.openshift.opentlc.comm/80ff-jenkins/jenkins-slave-maven-appdev:v3.9"

